services:
  #localhost-frontend:
    #image: alpine:latest
    #command: sleep infinity
    #container_name: selfcare_alpine
    #ports:
      #- "4200:4200" # frontend

  frontend:
    #image: selfcare-frontend
    image: schmidtwaldemar/selfcare-frontend:0.0.0
    container_name: selfcare-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    #network_mode: "service:localhost-frontend"
