services:
  frontend:
    image: schmidtwaldemar/selfcare-frontend:${VERSION}
    container_name: selfcare-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 80:8080
    networks:
      - "selfcare-network"
    environment:
      - BACKEND_HOST: ${VPS_BACKEND_HOST}
      - BACKEND_PORT: 8222
      - BACKEND_PROTOCOL_SCHEMA: 'http'
      - BACKEND_MODERATOR_PORT: 8040

networks:
  selfcare-network:
    driver: bridge