services:
  frontend:
    image: schmidtwaldemar/selfcare-frontend:${VERSION}
    container_name: selfcare-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 80:8080
    networks:
      - "selfcare-network"
    env_file: 'frontend/.env-frontend'

networks:
  selfcare-network:
    driver: bridge