/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MemberRequest {
  clientNumber?: string;
  groupId?: number;
  id?: number;
  nickname?: string;
}
