apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: selfcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      #- image: mongo:4.4.18
      - image: mongo:8.0-noble
        name: selfcare-mongodb
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: selfcare
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: selfcare
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - mountPath: "/data/db"
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {} 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: selfcare
spec:
  type: ClusterIP
  ports:
  - name: "mongo-service"
    port: 27017
    targetPort: 27017
  selector:
    app: mongo
  
