apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mariadb
  name: mariadb
  namespace: selfcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:latest
        name: selfcare-mariadb
        env:
        - name: MARIADB_USER
          value: root
        - name: MARIADB_PASSWORD
          value: selfcare
        - name: MARIADB_ROOT_PASSWORD
          value: selfcare
        ports:
        - containerPort: 5432
          name: mariadb
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {} 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb
  namespace: selfcare
spec:
  type: ClusterIP
  ports:
  - name: "mariadb-service"
    port: 3306
    targetPort: 3306
  selector:
    app: mariadb
  
