spring:
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:7080/realms/selfcare-management"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka