/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ModeratorRequest } from '../../models/moderator-request';
import { ModeratorResponse } from '../../models/moderator-response';

export interface ApiModeratorsCreatePost$Params {
      body?: ModeratorRequest
}

export function apiModeratorsCreatePost(http: HttpClient, rootUrl: string, params?: ApiModeratorsCreatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<ModeratorResponse>> {
  const rb = new RequestBuilder(rootUrl, apiModeratorsCreatePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ModeratorResponse>;
    })
  );
}

apiModeratorsCreatePost.PATH = '/api/moderators/create';
