spring:
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    bootstrap-servers: "localhost:9092"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:7080/realms/selfcare-management"
  datasource:
    url: jdbc:mariadb://localhost:3306/groupDB

application:
  config:
    participant-url: http://localhost:8222/api/participants

openapi:
  service:
    url: http://localhost:8222
    keycloakConnectionUrl: http://localhost:7080/realms/selfcare-management/protocol/openid-connect/auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka