/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ModeratorRequest } from './models/moderator-request';
export type { ModeratorResponse } from './models/moderator-response';
