apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: maildev
  name: maildev
  namespace: selfcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maildev
  template:
    metadata:
      labels:
        app: maildev
    spec:
      containers:
      - image: maildev/maildev
        name: selfcare-maildev
        ports:
        - containerPort: 1025
          name: maildev
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: maildev
  name: maildev
  namespace: selfcare
spec:
  type: ClusterIP
  ports:
  - name: "maildev-smtp"
    port: 1025
    targetPort: 1025
  - name: "maildev-admin"
    port: 1080
    targetPort: 1080
  selector:
    app: maildev
  
