apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: selfcare
spec:
  ports:
    - name: http
      port: 7080
      targetPort: 7080
  selector:
    app: keycloak
  type: ClusterIP
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: selfcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0.4
          args: ["start", "--cache-stack=kubernetes"]
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "admin"
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: "admin"
            - name: KC_HTTP_PORT
              value: "7080"
            - name: KEYCLOAK_FRONTEND_URL
              value: http://localhost:7080/auth
            - name: KC_HOSTNAME
              value: http://keycloak.selfcare.svc.cluster.local:7080
            - name: KC_PROXY
              value: "edge"
            - name: KC_PROXY_HEADERS
              value: xforwarded
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: "jdbc:postgresql://postgres.selfcare.svc.cluster.local:5432/keycloakdb"
            - name: KC_DB_USERNAME
              value: "postgres"
            - name: KC_DB_PASSWORD
              value: "selfcare"
            - name: jgroups.dns.query
              value: keycloak
          ports:
            - name: http
              containerPort: 7080