spring:
  datasource:
    username: root
    password: selfcare
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
  kafka:
    producer:
      bootstrap-servers: ${BACKEND_HOST}:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: groupMessage:com.platform.selfcare.kafka.GroupNotification
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://${BACKEND_HOST}:7080/realms/selfcare-management"

server:
  port: 8020
  
application:
  config:
    participant-url: http://${BACKEND_HOST}:8222/api/participants

openapi:
  service:
    title: openapi for group-service
    version: 1.0
    url: http://${BACKEND_HOST}:8222
    description: API zum verwalten von Selbsthilfegruppen
    licenceName: MIT license
    licenceUrl: https://github.com/SchmidtWaldemar/selfcare-management?tab=MIT-1-ov-file
    disclaimer: fuer die Inhalte wird keine Haftung uebernommen
    keycloakConnectionUrl: http://${BACKEND_HOST}:7080/realms/selfcare-management/protocol/openid-connect/auth

springdoc:
  api-docs:
    path: /group-service/v3/api-docs
  swagger-ui:
    path: /group-service/swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
