spring:
  datasource:
    username: root
    password: selfcare
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
  kafka:
    producer:
      #bootstrap-servers: selfcare_kafka:9092
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: groupMessage:com.platform.selfcare.kafka.GroupNotification
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:7080/realms/selfcare-management"
    cors:
      origin: http://192.168.178.157:8222/,http://192.168.178.157:7080/,http://localhost:4200/

server:
  port: 8020
  
application:
  config:
    #participant-url: http://selfcare-gateway:8222/api/participants
    participant-url: http://localhost:8222/api/participants

openapi:
  service:
    title: openapi for group-service
    version: 1.0
    #url: http://localhost:8222
    url: http://192.168.178.157:8222
    description: API zum verwalten von Selbsthilfegruppen
    licenceName: MIT license
    licenceUrl: https://github.com/SchmidtWaldemar/selfcare-management?tab=MIT-1-ov-file
    disclaimer: fuer die Inhalte wird keine Haftung uebernommen
    keycloakConnectionUrl: http://192.168.178.157:7080/realms/selfcare-management/protocol/openid-connect/auth

springdoc:
  api-docs:
    path: /group-service/v3/api-docs
  swagger-ui:
    path: /group-service/swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
