spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/groupDB
    username: root
    password: selfcare
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect

server:
  port: 8020