spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/groupDB
    username: root
    password: selfcare
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: groupMessage:com.platform.selfcare.kafka.GroupNotification
server:
  port: 8020
  
application:
  config:
    participant-url: http://localhost:8222/api/participants