spring:
  data:
    mongodb:
      username: selfcare
      password: selfcare
      host: localhost
      posrt: 27017
      database: notification
      authentication-database: admin

server:
  port: 8030