spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/participantDB
    username: postgres
    password: selfcare
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: participantMessage:com.platform.selfcare.kafka.ParticipantNotification
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:7080/realms/selfcare-management"

server:
  port: 8010

openapi:
  service:
    title: openapi for participant-service
    version: 1.0
    #url: http://selfcare-gateway:8222
    url: http://localhost:8222
    description: API zum verwalten von Teilnehmern
    licenceName: MIT license
    licenceUrl: https://github.com/SchmidtWaldemar/selfcare-management?tab=MIT-1-ov-file
    disclaimer: fuer die Inhalte wird keine Haftung uebernommen
    keycloakConnectionUrl: http://localhost:7080/realms/selfcare-management/protocol/openid-connect/auth

springdoc:
  api-docs:
    path: /participant-service/v3/api-docs
  swagger-ui:
    path: /participant-service/swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
