apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: discovery
  name: discovery
  namespace: selfcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
      namespace: selfcare
    spec:
      containers:
      - image: schmidtwaldemar/selfcare-discovery-k8s:latest
        name: discovery
        ports:
        - containerPort: 8761
          name: discovery
---
apiVersion: v1
kind: Service
metadata:
  name: discovery
  namespace: selfcare
spec:
  selector:
    app: discovery
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761
  selector:
    app: discovery
